config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  root 'home#welcome'
  
  get '/about_us', to: 'home#about_us'

  get '/buying_tools', to: 'home#buying_tools'

  resources :drivers


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/driver.rb
class Driver < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController

    def new
        @driver = Driver.new 
    end

    def show 
        @driver = Driver.find(params[:id])
    end

    def create
        #raise params.inspect
        @driver = Driver.new(driver_params)
        if @driver.save!
            flash[:notice] = "Congrats #{@driver.first_name}, you will be contacted within the next 24 hours!"
            redirect_to driver_path(@driver)
        else
            @driver.errors.full_messages
            redirect_to 'new'
        end
    end

    def edit

    end

    def update 
    end

    private 

    def driver_params 
        params.require(:driver).permit(:first_name, :last_name, :address, :apt, :city, :state, :zip, :residence_type, :monthly_housing_cost, :address_duration_years, :address_duration_months, :phone, :email, :dob, :ssn, :bankruptcy, :employment_type, :employer_name, :employer_phone_number, :job_title, :job_duration_years, :job_duration_months, :monthly_income)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/drivers/new.html.erb
<div class="main-form">
    <div class="appey">
        <div class="title">
        <h1>Applicant Registration Form</h1>
        </div>
        <%= form_for(@driver) do |f| %>

        <div class="form-label-group-left">
            <%= f.text_field :first_name, placeholder: "First Name" %>
        </div>

        <div class="form-label-group-right">
            <%= f.text_field :last_name, placeholder: "Last Name" %>
        </div>

        <div class="form-label-group-left">
            <%= f.text_field :address, placeholder: "Street Address" %>
        </div>

        <div class="form-label-group-right">
            <%= f.text_field :apt, placeholder: "Apt. #" %>
        </div>

        <div class="form-label-group-left">
            <%= f.text_field :city, placeholder: "City" %>
        </div>

        <div class="form-label-group-right">
            <%= f.label :state, "State:" %>
            <%= f.select :state, [["select state"], ["AK"], ["AL"], ["AR"], ["AZ"], ["CA"], ["CO"], 
                ["CT"], ["DC"], ["DE"], ["FL"], ["GA"], ["HI"], ["IA"], ["ID"], ["IL"], 
                ["IN"], ["KS"], ["KY"], ["LA"], ["MA"], ["MD"], ["ME"], ["MI"], ["MN"], 
                ["MO"], ["MS"], ["MT"], ["NC"], ["ND"], ["NE"], ["NH"], ["NJ"], ["NM"], 
                ["NV"], ["NY"], ["OH"], ["OK"], ["OR"], ["PA"], ["RI"], ["SC"], ["SD"], 
                ["TN"], ["TX"], ["UT"], ["VA"], ["VT"], ["WA"], ["WI"], ["WV"], ["WY"]] %>
        </div>

        <div class="form-label-group-left">
            <%= f.text_field :zip, placeholder: "Zip Code" %>
        </div>

        <div class="form-label-group-right">
            <%= f.label :residence_type, "Residence Type:" %>
            <%= f.select :residence_type, [["select type"], ['Lives w/ Relatives'], ['Own Home Outright'], ['Rent'], ['Mortgage']] %>
        </div>

        <div class="form-label-group-left">
            <%= f.label :monthly_housing_cost, "Monthly Housing Cost: $" %>
            <%= f.select :monthly_housing_cost, [["-"], ["300"], ["350"], ["400"], ["450"], ["500"], ["550"],
                                ["600"], ["650"], ["700"], ["750"], ["800"], ["850"], ["900"], ["950"],
                                ["1000"], ["1100"], ["1200"], ["1300"], ["1400"], ["1500"], ["1600"],
                                ["1700"], ["1800"], ["1900"], ["2000"]] %>
        </div>

        <div class="form-label-group-right">
            <%= f.label :address_duration_years, "Time at address? "%>
            <%= f.select :address_duration_years, [["years"], ["1"], ["2"], ["3"], ["4"], ["5"], ["6"], ["7"], ["8"], ["9"], ["10"], ["11"], ["12"], ["13"], ["14"],
                                ["15"], ["16"], ["17"], ["18"], ["19"], ["20"]] %><%= f.select :address_duration_months, [["months"], ["1"], ["2"], ["3"], ["4"], ["5"], ["6"], ["7"], ["8"], ["9"], ["10"], ["11"]] %>
        </div>

        <div class="form-label-group-left">
            <%= f.text_field :phone, placeholder: "Phone Number (no-dashes)" %>
        </div>

        <div class="form-label-group-right">
            <%= f.email_field :email, placeholder: "Email Address" %>
        </div>

        <div class="form-label-group-left">
            <%= f.text_field :dob, placeholder: "Date of Birth / mmddyyyy" %>
        </div>

        <div class="form-label-group-right">
            <%= f.text_field :ssn, placeholder: "Soc. Security Number (no-dashes)" %>
        </div>

        <div class="form-label-group-left">
            <%= f.label :bankruptcy, "Bankruptcy last 5 years?:" %>(check box if yes)
            <%= f.check_box :bankruptcy %> 
        </div>

        <div class="form-label-group-right">
            <%= f.label :employment_type, "Employment Type:" %>
            <%= f.select :employment_type, [["select type"], ['Employed Full-Time'], ['Employed Part-Time'], ['Self-Employed'], ['Social Security'], ['Fixed-Income'], ['Unemployed'], ['Student']] %>
        </div>

        <div class="form-label-group-left">
            <%= f.text_field :employer_name, placeholder: "Employer Name" %>
        </div>

        <div class="form-label-group-right">
            <%= f.text_field :job_title, placeholder: "Job Title" %>
        </div>

        <div class="form-label-group-left">
            <%= f.text_field :employer_phone_number, placeholder: "Employer Phone Number (no-dashes)" %>
        </div>

        <div class="form-label-group-right">
            <%= f.label :job_duration, "Time on Job:"%>
            <%= f.select :job_duration_years, [["years"], ["1"], ["2"], ["3"], ["4"], ["5"], ["6"], ["7"], ["8"], ["9"], ["10"], ["11"], ["12"], ["13"], ["14"],
                                ["15"], ["16"], ["17"], ["18"], ["19"], ["20"]] %><%= f.select :job_duration_months, [["months"], ["1"], ["2"], 
                                ["3"], ["4"], ["5"], ["6"], ["7"], ["8"], ["9"], ["10"], ["11"]] %>
        </div>

        <div class="form-label-group-left">
            <%= f.label :monthly_income, "Gross Monthly Income: $" %>
            <%= f.select :monthly_income, [["-"], ["400"], ["450"], ["500"], ["550"],
                                ["600"], ["650"], ["700"], ["750"], ["800"], ["850"], ["900"], ["950"],
                                ["1000"], ["1100"], ["1200"], ["1300"], ["1400"], ["1500"], ["1600"],
                                ["1700"], ["1800"], ["1900"], ["2000"], ["2100"], ["2200"], ["2300"], ["2400"],
                                ["2500"], ["2600"], ["2700"], ["2800"], ["2900"], ["3000"], ["3100"], ["3200"],
                                ["3300"], ["3400"], ["3500"], ["3600"], ["3700"], ["3800"], ["3900"],
                                ["4000"], ["4100"], ["4200"], ["4300"], ["4400"], ["4500"], ["4600"],
                                ["4700"], ["4800"], ["4900"], ["5000"], ["5100"], ["5200"], ["5300"],
                                ["5400"], ["5500"], ["5600"], ["5700"], ["5800"], ["5900"], ["6000"]] %>
        </div>

        <div class="form-label-group">
            <%= f.submit "Get Driving Now", class: "btn btn-success btn-lg" %>
        </div>

        <% end %>
    </div>
</div>

app/views/drivers/show.html.erb
<div class="show-page">
  <div class="show-words">
    <div class="container">
      
      <h2>Congratulations <%= @driver.first_name %>,</h2>
        <h4>Please standby for an email with a reciept confirmation number soon.</h4>
          <h4>Items you may need to gather:</h4>
        <ul>
          <li>Government or State ID</li>
          <li>Most recent Paystubs</li>
          <li>Utility Bill in your name to address on application</li>
          <li>Title to Trade-in if applicable</li>
          <li>Payoff information on Trade-in if applicable</li>
          <li>Insurance Information</li>
          <li>Your Downpayment</li>
        </ul>
        <h5>You will be contacted within 24hrs by a highly trained, successful 
            finance professional embedded in one of our many trusted local 
            dealerships with inventory ready to go!</h5>
    </div>
  </div>
</div>
 

app/views/home/about_us.html.erb
<h1>About us</h1>

app/views/home/buying_tools.html.erb
<h1>Buying tools</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GetDrivingNow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>

  <div class="top-nav"> 
    <div class="nav-link-logo" >
      <a href="/"><%= image_tag "LogoGye2.jpeg", height:"50" %></a>
    </div>   
    
    <p><%= link_to "Get Started", new_driver_path %></p>
    <p><%= link_to "Car Buying Tools", buying_tools_path %></p>
    <p><%= link_to "About Us", about_us_path %></p>
  </div>
  <div class="disaster">
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <%= link_to "Login", new_user_session_path %>
  </div>
    



    
  
    <%= yield %>


  </body>
</html>

app/views/users/new.html.erb
<div class="main-app-class">
<h1>Applicant Registration Form</h1>

<%= form_for(@user) do |f| %>

<div class="main-app-element">
<%= f.label :first_name, "First Name:" %>
<%= f.text_field :first_name, placeholder: "First Name" %>
</div>
<div class="main-app-element">
<%= f.label :last_name, "Last Name:" %>
<%= f.text_field :last_name %>
</div>
<div class="main-app-element">
<%= f.label :address, "Address:"%>
<%= f.text_field :address %>
</div>
<div class="main-app-element">
<%= f.label :apt, "Apt #:" %>
<%= f.text_field :apt %>
</div>
<div class="main-app-element">
<%= f.label :city, "City:" %>
<%= f.text_field :city %>
</div>
<div class="main-app-element">
<%= f.label :state, "State:" %>
<%= select_tag "State", options_for_select([["AK"], 
                ["AL"], 
                ["AR"], 
                ["AZ"], 
                ["CA"], 
                ["CO"], 
                ["CT"], 
                ["DC"], 
                ["DE"], 
                ["FL"], 
                ["GA"], 
                ["HI"], 
                ["IA"], 
                ["ID"], 
                ["IL"], 
                ["IN"], 
                ["KS"], 
                ["KY"], 
                ["LA"], 
                ["MA"], 
                ["MD"], 
                ["ME"], 
                ["MI"], 
                ["MN"], 
                ["MO"], 
                ["MS"], 
                ["MT"], 
                ["NC"], 
                ["ND"], 
                ["NE"], 
                ["NH"], 
                ["NJ"], 
                ["NM"], 
                ["NV"], 
                ["NY"], 
                ["OH"], 
                ["OK"], 
                ["OR"], 
                ["PA"], 
                ["RI"], 
                ["SC"], 
                ["SD"], 
                ["TN"], 
                ["TX"], 
                ["UT"], 
                ["VA"], 
                ["VT"], 
                ["WA"], 
                ["WI"], 
                ["WV"], 
                ["WY"]
]) %>
</div>
<div class="main-app-element">
<%= f.label :zip, "Zip:" %>
<%= f.text_field :zip %>
</div>
<div class="main-app-element">
<%= f.label :residence_type, "Residence Type:" %>
<%= select_tag "Residence Type", options_for_select([['Lives w/ Relatives'], ['Own Home Outright'], ['Rent'], ['Mortgage']]) %>

</div>
<div class="main-app-element">
<%= f.label :monthly_housing_cost, "Monthly Housing Cost:" %>
<%= f.text_field :monthly_housing_cost %>
</div>
<div class="main-app-element">
<%= f.label :address_duration, "How long at current address?:" %>
<%= f.text_field :address_duration %>
</div>
<div class="main-app-element">
<%= f.label :phone, "Phone Number:" %>
<%= f.text_field :phone %>
</div>
<div class="main-app-element">
<%= f.label :email, "Email Address:" %>
<%= f.email_field :email %>
</div>
<div class="main-app-element">
<%= f.label :dob, "Date of Birth:" %>
<%= f.text_field :dob, placeholder: "mmddyear" %>
</div>
<div class="main-app-element">
<%= f.label :ssn, "Social Security Number:" %>
<%= f.text_field :ssn, placeholder: "xxx-xx-xxxx" %>
</div>
<div class="main-app-element">
<%= f.label :bankruptcy, "Have you declared Bankruptcy within the last 5 years?:" %>
<%= f.check_box :bankruptcy %> (check box if yes)
</div>
<div class="main-app-element">
<%= f.label :employment_type, "Employment Type:" %>
<%= select_tag "Employment Type", options_for_select([['Employed Full-Time'], ['Employed Part-Time'], ['Social Security'], ['Fixed-Income'], ['Unemployed'], ['Student']]) %>
</div>
<div class="main-app-element">
<%= f.label :employer_name, "Employer Name:" %>
<%= f.text_field :employer_name %>
</div>
<div class="main-app-element">
<%= f.label :job_title, "Job Title:" %>
<%= f.text_field :job_title %>
</div>
<div class="main-app-element">
<%= f.label :employer_phone_number, "Job Number:" %>
<%= f.text_field :employer_phone_number %>
</div>
<div class="main-app-element">
<%= f.label :job_duration, "Time at Job:" %>
<%= f.text_field :job_duration %>
</div>
<div class="main-app-element">
<%= f.label :monthly_income, "Gross Monthly Income:" %>
<%= f.text_field :monthly_income %>
</div>
<div class="main-app-element">
<%= f.submit "Submit Your Application" %>
</div>
<% end %>
</div>